CREATE TABLE TblSupplier (
  SupplierName VARCHAR2(1000) NOT NULL,
  SupplierContactName VARCHAR2(1000) NOT NULL,
  SupplierAddress VARCHAR2(1000) NOT NULL,
  CONSTRAINT supplier_pk PRIMARY KEY (SupplierName)
);

CREATE TABLE TblSupplierContact (
  ContactId      NUMBER        GENERATED BY DEFAULT ON NULL AS IDENTITY,
  SupplierName VARCHAR2(1000) NOT NULL,
  SupplierContactNumber NUMBER NOT NULL,
  CONSTRAINT suppliercontact_pk PRIMARY KEY (ContactId),
  CONSTRAINT suppliercontact_fk
    FOREIGN KEY (SupplierName)
    REFERENCES TblSupplier(SupplierName)
);


CREATE TABLE TblOrders (
  OrderId      NUMBER        GENERATED BY DEFAULT ON NULL AS IDENTITY,
  OrderReference   VARCHAR2(100) NOT NULL,
  OrderDate Date NOT NULL,
  OrderTotalAmount float ,
  OrderDescription VARCHAR2(1000),
  OrderStatus VARCHAR2(100) NOT NULL,
  OrderLineAmount float,
  SupplierName  VARCHAR2(1000) NOT NULL,
  CONSTRAINT orders_pk PRIMARY KEY (OrderId),
  CONSTRAINT supplier_fk
    FOREIGN KEY (SupplierName)
    REFERENCES TblSupplier(SupplierName)
);

CREATE TABLE TblInvoice(
  InvoiceID      NUMBER        GENERATED BY DEFAULT ON NULL AS IDENTITY,
  InvoiceReference   VARCHAR2(100),
  InvoiceDate Date ,
  InvoiceStatus VARCHAR2(100) ,
  InvoiceHoldReason VARCHAR2(1000),
  InvoiceDescription VARCHAR2(1000),
  InvoiceAmount float,
  OrderId NUMBER NOT NULL,
  CONSTRAINT invoice_pk PRIMARY KEY (InvoiceID),
  CONSTRAINT invoice_fk
    FOREIGN KEY (OrderId)
    REFERENCES TblOrders(OrderId)
);



CREATE TABLE TblSupplierContactTemp (
    SupplierName VARCHAR2(1000),
    SUPPLIERCONTACTNUMBER1 NUMBER,
    SUPPLIERCONTACTNUMBER2 NUMBER,
    GUID VARCHAR2(1000 BYTE)
);